project_id = "ibxzyodvtmagnetpyyfz"

[functions.extract-documento]
verify_jwt = false

[functions.extract-extrato]
verify_jwt = false

[functions.generate-sugestoes]
verify_jwt = false

[functions.create-user]
verify_jwt = false